priority=10
requires-package=harbour-bugger
icon=icon-m-new-bug
title="Report a bug!"
remote-service="sailfishos-chum.Bugger.ui"
remote-path="/sailfishos_chum/Bugger/ui"
remote-interface="sailfishos-chum.Bugger.ui"
remote-method="newBug"
remote-arguments=[""]
