priority=10
requires-package=harbour-bugger
icon=icon-m-new-bug
title="Report a bug!"
remote-service="sailfishos-chum.Bugger"
remote-path="/ui"
remote-interface="sailfishos-chum.Bugger"
remote-method="newBug"
remote-arguments=[""]
